/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE, Connor built off of that boiler plate to blink an LED
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************

- use pa_5 for in pin 5 for LED and either pc_13 or pa_13 for Button
- EXTI # same as pin #


 ******************************************************************************
 */

#include <stdint.h>

volatile uint8_t  button_mode = 0;

#define RCC_AHB1ENR (*(volatile uint32_t *) 0x40023830) // bus for GPIOA
#define RCC_APB1ENR (*(volatile uint32_t *) 0x40023840) // bus for timer

#define RCC_APB2ENR (*(volatile uint32_t *) 0x40023844) // bus for SYSCFG

#define TIM2_CR1 (*(volatile uint32_t *) 0x40000000) // Turn on timer
#define TIM2_PSC (*(volatile uint32_t *) (0x40000000 + 0x28U)) //Timer PSC
#define TIM2_ARR (*(volatile uint32_t *) (0x40000000 + 0x2C)) //TIMER ARR
#define TIM2_DIER (*(volatile uint32_t *) (0x40000000 + 0x0C)) // interrupt enable
#define TIM2_SR (*(volatile uint32_t *) (0x40000000 + 0x10)) // status register

//#define GPIOA_AFRL (*(volatile uint32_t *) (0x40020000 + 0x20)) //
#define GPIOA_MODER (*(volatile uint32_t *) (0x40020000 + 0)) // MODE R
#define GPIOA_ODR (*(volatile uint32_t *) (0x40020000 + 0x14)) //
#define GPIOA_BSRR (*(volatile uint32_t *) (0x40020000 + 0x18)) //

#define GPIOC_MODER (*(volatile uint32_t *) (0x40020800 + 0x00))
#define GPIOC_PUPDR (*(volatile uint32_t *) (0x40020800 + 0x0C))
#define GPIOC_IDR (*(volatile uint32_t *) (0x40020800 + 0x10))

//#define TIM2_CCMR1 (*(volatile uint32_t *) (0x40000000 + 0x18)) // mode register -> PWM
//#define TIM2_CCER (*(volatile uint32_t *) (0x40000000 + 0x20)) // enable reg
#define TIM2_CCR1 (*(volatile uint32_t *) (0x40000000 + 0x34)) // Set PWM cycle

#define NVIC_ISER0 (*(volatile uint32_t *) (0xE000E000 + 0x100 + 0x04 * 0))
#define NVIC_ISER1 (*(volatile uint32_t *) (0xE000E000 + 0x100 + 0x04 * 1))

#define SYSCFG_EXTICR4 (*(volatile uint32_t *) (0x40013800 + 0x14))
#define EXTI_IMR (*(volatile uint32_t *) (0x40013C00 + 0x00))
#define EXTI_FTSR (*(volatile uint32_t *) (0x40013C00 + 0x0C))
#define EXTI_PR (*(volatile uint32_t *) (0x40013C00 + 0x14))

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void INIT(void) {
	RCC_AHB1ENR |= (1U << 0); // turn on for GPIOA
	RCC_AHB1ENR |= (1U << 2); // turn on for GPIOC
	RCC_APB1ENR |= (1U << 0); // turn on for TIM2
	RCC_APB2ENR |= (1u << 14); // turn on SYSCLK

	// Setup up TIM2 and corresponding interrupt
//	TIM2_CR1	|= (1U << 0); // Set timer
	TIM2_PSC	= 1600 -1;
	TIM2_ARR	= 1000 -1;

	TIM2_DIER |= (1U << 0);
//	TIM2_CCER |= (1U << 0); // enable

	NVIC_ISER0 |= (1U << 28);
	NVIC_ISER1 |= (1U << (40-32));
//
//	 // set PWM
//	TIM2_CCMR1	&= ~(0x3U << (0));
//	TIM2_CCMR1	&= ~(0x7U << (4));
//	TIM2_CCMR1	|= (0x6U << (4));
//	TIM2_CCMR1	|= (0x1U << (3));

	// Get GPIOA working
	GPIOA_MODER	&= ~(0x3U << (5 * 2));
	GPIOA_MODER	|= (0x1U << (5 * 2));
//
//	GPIOA_AFRL	&= ~(0xFU << (5 * 4));
//	GPIOA_AFRL	|= (0x1U << (5 * 4));

	// Get GPIOC working
	GPIOC_MODER &= ~(0x3U << (13 * 2));

	GPIOC_PUPDR &= ~(0x3U << (13 * 2));
	GPIOC_PUPDR |= (0x1U << (13 * 2));

	//
	SYSCFG_EXTICR4 &= ~(0x0FU << 4);
	SYSCFG_EXTICR4 |= (0x02U << 4);

	EXTI_FTSR |= (1U << 13);
	EXTI_IMR |= (1U << 13);
}

void EXTI15_10_IRQHandler () { /*button is pressed -> add a debounce*/
	if (EXTI_PR & (1U << 13)) {
		EXTI_PR = (1U << 13);
		if (button_mode == 2) {
			button_mode = 0;
		}
		else {
			button_mode++;
		}
	}
}

void TIM2_IRQHandler(void) {
	if (TIM2_SR & (1U << 0)) {
		TIM2_SR &= ~(1U << 0); // reset flag
		uint32_t current_state = GPIOA_ODR;
		if (!(current_state & (1U << 5))) {
			GPIOA_BSRR = (1U << 5); // set LED on
		}
		if (current_state & (1U << 5)) {
			GPIOA_BSRR = (1U << 5 + 16); // set LED off
		}
	}
}

int main(void)
{
	INIT();
    /* Loop forever */
	while(1) {
		if (button_mode == 0) {
			TIM2_CR1 &= ~(1U << 0); // disable timer
			GPIOA_BSRR = (1U << 5 + 16); // set LED off
			// Off
			// Set bit in register to tell light to be off
		}
		else if (button_mode == 1) {
			TIM2_CR1 &= ~(1U << 0); // disable timer
			GPIOA_BSRR = (1U << 5); // set LED on
			// on
			// Set bit in register to tell light to be on
		}
		else if (button_mode == 2) {
			// flashing
			// Somehow tie bit in register to timer that toggles between on and off. IDK how, I'll save this for last.
			TIM2_CR1 |= (1U << 0); // enable timer
		}
	}
}
